### ISSUE TITLE
[0.0.1-alpha] Missing Wireframing Lo-Fi

### ISSUE THREAD

**Issue by samanthabaita** [revas/universo#1]
- [x] I am not here to ask for information or support.
- [x] I have searched in the issue track but found nothing.

**Comment by hashbardd** [comment]
I merged the specs documentation, @revas/designers can now start with this issue discussion!

**Comment by lucyskyy** [comment]
I can't understand the layout of the grid. Is it responsive? The items have fixed width? How many objects can I put on in a row?
@revas/designers
