### ISSUE TITLE
Missing Specs Documentation

### ISSUE THREAD

**Issue by davidegiovanni** [revas/universo#4]
- [x] I am not here to ask for information or support.
- [x] I have searched in the issue track but found nothing.

## Context

We have defined the revo context and now we need the specification document.

**Comment by hashbardd** [comment]
Thank you @davidegiovanni ! Would you like to submit a PR? The branch name could be `docs/4-specs-docs`

**Comment by davidegiovanni** [comment]
Yes, I will do it 👍
